sonar.projectKey=defra_fcp-sfd-frontend-engine
sonar.organization=defra

sonar.sources=src/
sonar.tests=test/

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.coverage.exclusions=src/assets/**
sonar.exclusions=scripts/**